# Usar la imagen oficial de Nginx (versión Alpine por ligereza)
FROM nginx:alpine

# Copiar todos los archivos estáticos del frontend al directorio por defecto de Nginx
COPY . /usr/share/nginx/html
